package org.lemonframework.generator.sample.dao.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class AppointmentRecordExample implements Serializable {
    /**
     * 序列号.
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * @return
     *
     * @mbg.generated
     */
    public AppointmentRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * @param orderByClause orderByClause
     * @return
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return String
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @param distinct distinct
     * @return
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return boolean
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return List<Criteria>
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @param criteria criteria
     * @return
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return Criteria
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return Criteria
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return Criteria
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * @return
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeIsNull() {
            addCriterion("weahan_code is null");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeIsNotNull() {
            addCriterion("weahan_code is not null");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeEqualTo(String value) {
            addCriterion("weahan_code =", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeNotEqualTo(String value) {
            addCriterion("weahan_code <>", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeGreaterThan(String value) {
            addCriterion("weahan_code >", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeGreaterThanOrEqualTo(String value) {
            addCriterion("weahan_code >=", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeLessThan(String value) {
            addCriterion("weahan_code <", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeLessThanOrEqualTo(String value) {
            addCriterion("weahan_code <=", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeLike(String value) {
            addCriterion("weahan_code like", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeNotLike(String value) {
            addCriterion("weahan_code not like", value, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeIn(List<String> values) {
            addCriterion("weahan_code in", values, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeNotIn(List<String> values) {
            addCriterion("weahan_code not in", values, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeBetween(String value1, String value2) {
            addCriterion("weahan_code between", value1, value2, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andWeahanCodeNotBetween(String value1, String value2) {
            addCriterion("weahan_code not between", value1, value2, "weahanCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdIsNull() {
            addCriterion("organization_root_id is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdIsNotNull() {
            addCriterion("organization_root_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdEqualTo(Long value) {
            addCriterion("organization_root_id =", value, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdNotEqualTo(Long value) {
            addCriterion("organization_root_id <>", value, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdGreaterThan(Long value) {
            addCriterion("organization_root_id >", value, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdGreaterThanOrEqualTo(Long value) {
            addCriterion("organization_root_id >=", value, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdLessThan(Long value) {
            addCriterion("organization_root_id <", value, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdLessThanOrEqualTo(Long value) {
            addCriterion("organization_root_id <=", value, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdIn(List<Long> values) {
            addCriterion("organization_root_id in", values, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdNotIn(List<Long> values) {
            addCriterion("organization_root_id not in", values, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdBetween(Long value1, Long value2) {
            addCriterion("organization_root_id between", value1, value2, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andOrganizationRootIdNotBetween(Long value1, Long value2) {
            addCriterion("organization_root_id not between", value1, value2, "organizationRootId");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Integer> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Integer> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(Long value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(Long value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(Long value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(Long value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(Long value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(Long value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<Long> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<Long> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(Long value1, Long value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(Long value1, Long value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientNameIsNull() {
            addCriterion("patient_name is null");
            return (Criteria) this;
        }

        public Criteria andPatientNameIsNotNull() {
            addCriterion("patient_name is not null");
            return (Criteria) this;
        }

        public Criteria andPatientNameEqualTo(String value) {
            addCriterion("patient_name =", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotEqualTo(String value) {
            addCriterion("patient_name <>", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameGreaterThan(String value) {
            addCriterion("patient_name >", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameGreaterThanOrEqualTo(String value) {
            addCriterion("patient_name >=", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLessThan(String value) {
            addCriterion("patient_name <", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLessThanOrEqualTo(String value) {
            addCriterion("patient_name <=", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLike(String value) {
            addCriterion("patient_name like", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotLike(String value) {
            addCriterion("patient_name not like", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameIn(List<String> values) {
            addCriterion("patient_name in", values, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotIn(List<String> values) {
            addCriterion("patient_name not in", values, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameBetween(String value1, String value2) {
            addCriterion("patient_name between", value1, value2, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotBetween(String value1, String value2) {
            addCriterion("patient_name not between", value1, value2, "patientName");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountIsNull() {
            addCriterion("appointment_amount is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountIsNotNull() {
            addCriterion("appointment_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountEqualTo(Integer value) {
            addCriterion("appointment_amount =", value, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountNotEqualTo(Integer value) {
            addCriterion("appointment_amount <>", value, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountGreaterThan(Integer value) {
            addCriterion("appointment_amount >", value, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("appointment_amount >=", value, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountLessThan(Integer value) {
            addCriterion("appointment_amount <", value, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountLessThanOrEqualTo(Integer value) {
            addCriterion("appointment_amount <=", value, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountIn(List<Integer> values) {
            addCriterion("appointment_amount in", values, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountNotIn(List<Integer> values) {
            addCriterion("appointment_amount not in", values, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountBetween(Integer value1, Integer value2) {
            addCriterion("appointment_amount between", value1, value2, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("appointment_amount not between", value1, value2, "appointmentAmount");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateIsNull() {
            addCriterion("appointment_date is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateIsNotNull() {
            addCriterion("appointment_date is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateEqualTo(String value) {
            addCriterion("appointment_date =", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateNotEqualTo(String value) {
            addCriterion("appointment_date <>", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateGreaterThan(String value) {
            addCriterion("appointment_date >", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateGreaterThanOrEqualTo(String value) {
            addCriterion("appointment_date >=", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateLessThan(String value) {
            addCriterion("appointment_date <", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateLessThanOrEqualTo(String value) {
            addCriterion("appointment_date <=", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateLike(String value) {
            addCriterion("appointment_date like", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateNotLike(String value) {
            addCriterion("appointment_date not like", value, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateIn(List<String> values) {
            addCriterion("appointment_date in", values, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateNotIn(List<String> values) {
            addCriterion("appointment_date not in", values, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateBetween(String value1, String value2) {
            addCriterion("appointment_date between", value1, value2, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentDateNotBetween(String value1, String value2) {
            addCriterion("appointment_date not between", value1, value2, "appointmentDate");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeIsNull() {
            addCriterion("appointment_time is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeIsNotNull() {
            addCriterion("appointment_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeEqualTo(String value) {
            addCriterion("appointment_time =", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeNotEqualTo(String value) {
            addCriterion("appointment_time <>", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeGreaterThan(String value) {
            addCriterion("appointment_time >", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeGreaterThanOrEqualTo(String value) {
            addCriterion("appointment_time >=", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeLessThan(String value) {
            addCriterion("appointment_time <", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeLessThanOrEqualTo(String value) {
            addCriterion("appointment_time <=", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeLike(String value) {
            addCriterion("appointment_time like", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeNotLike(String value) {
            addCriterion("appointment_time not like", value, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeIn(List<String> values) {
            addCriterion("appointment_time in", values, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeNotIn(List<String> values) {
            addCriterion("appointment_time not in", values, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeBetween(String value1, String value2) {
            addCriterion("appointment_time between", value1, value2, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeNotBetween(String value1, String value2) {
            addCriterion("appointment_time not between", value1, value2, "appointmentTime");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoIsNull() {
            addCriterion("appointment_no is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoIsNotNull() {
            addCriterion("appointment_no is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoEqualTo(Integer value) {
            addCriterion("appointment_no =", value, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoNotEqualTo(Integer value) {
            addCriterion("appointment_no <>", value, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoGreaterThan(Integer value) {
            addCriterion("appointment_no >", value, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("appointment_no >=", value, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoLessThan(Integer value) {
            addCriterion("appointment_no <", value, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoLessThanOrEqualTo(Integer value) {
            addCriterion("appointment_no <=", value, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoIn(List<Integer> values) {
            addCriterion("appointment_no in", values, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoNotIn(List<Integer> values) {
            addCriterion("appointment_no not in", values, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoBetween(Integer value1, Integer value2) {
            addCriterion("appointment_no between", value1, value2, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentNoNotBetween(Integer value1, Integer value2) {
            addCriterion("appointment_no not between", value1, value2, "appointmentNo");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutIsNull() {
            addCriterion("appointment_timeout is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutIsNotNull() {
            addCriterion("appointment_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutEqualTo(Integer value) {
            addCriterion("appointment_timeout =", value, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutNotEqualTo(Integer value) {
            addCriterion("appointment_timeout <>", value, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutGreaterThan(Integer value) {
            addCriterion("appointment_timeout >", value, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("appointment_timeout >=", value, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutLessThan(Integer value) {
            addCriterion("appointment_timeout <", value, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("appointment_timeout <=", value, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutIn(List<Integer> values) {
            addCriterion("appointment_timeout in", values, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutNotIn(List<Integer> values) {
            addCriterion("appointment_timeout not in", values, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("appointment_timeout between", value1, value2, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("appointment_timeout not between", value1, value2, "appointmentTimeout");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusIsNull() {
            addCriterion("appointment_status is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusIsNotNull() {
            addCriterion("appointment_status is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusEqualTo(Byte value) {
            addCriterion("appointment_status =", value, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusNotEqualTo(Byte value) {
            addCriterion("appointment_status <>", value, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusGreaterThan(Byte value) {
            addCriterion("appointment_status >", value, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("appointment_status >=", value, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusLessThan(Byte value) {
            addCriterion("appointment_status <", value, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusLessThanOrEqualTo(Byte value) {
            addCriterion("appointment_status <=", value, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusIn(List<Byte> values) {
            addCriterion("appointment_status in", values, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusNotIn(List<Byte> values) {
            addCriterion("appointment_status not in", values, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusBetween(Byte value1, Byte value2) {
            addCriterion("appointment_status between", value1, value2, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andAppointmentStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("appointment_status not between", value1, value2, "appointmentStatus");
            return (Criteria) this;
        }

        public Criteria andOfficeIdIsNull() {
            addCriterion("office_id is null");
            return (Criteria) this;
        }

        public Criteria andOfficeIdIsNotNull() {
            addCriterion("office_id is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeIdEqualTo(Long value) {
            addCriterion("office_id =", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotEqualTo(Long value) {
            addCriterion("office_id <>", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdGreaterThan(Long value) {
            addCriterion("office_id >", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("office_id >=", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdLessThan(Long value) {
            addCriterion("office_id <", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdLessThanOrEqualTo(Long value) {
            addCriterion("office_id <=", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdIn(List<Long> values) {
            addCriterion("office_id in", values, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotIn(List<Long> values) {
            addCriterion("office_id not in", values, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdBetween(Long value1, Long value2) {
            addCriterion("office_id between", value1, value2, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotBetween(Long value1, Long value2) {
            addCriterion("office_id not between", value1, value2, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIsNull() {
            addCriterion("office_name is null");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIsNotNull() {
            addCriterion("office_name is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeNameEqualTo(String value) {
            addCriterion("office_name =", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotEqualTo(String value) {
            addCriterion("office_name <>", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameGreaterThan(String value) {
            addCriterion("office_name >", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameGreaterThanOrEqualTo(String value) {
            addCriterion("office_name >=", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLessThan(String value) {
            addCriterion("office_name <", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLessThanOrEqualTo(String value) {
            addCriterion("office_name <=", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLike(String value) {
            addCriterion("office_name like", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotLike(String value) {
            addCriterion("office_name not like", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIn(List<String> values) {
            addCriterion("office_name in", values, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotIn(List<String> values) {
            addCriterion("office_name not in", values, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameBetween(String value1, String value2) {
            addCriterion("office_name between", value1, value2, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotBetween(String value1, String value2) {
            addCriterion("office_name not between", value1, value2, "officeName");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Long value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Long value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Long value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Long value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Long value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Long> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Long> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Long value1, Long value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Long value1, Long value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNull() {
            addCriterion("doctor_name is null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNotNull() {
            addCriterion("doctor_name is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameEqualTo(String value) {
            addCriterion("doctor_name =", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotEqualTo(String value) {
            addCriterion("doctor_name <>", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThan(String value) {
            addCriterion("doctor_name >", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_name >=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThan(String value) {
            addCriterion("doctor_name <", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThanOrEqualTo(String value) {
            addCriterion("doctor_name <=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLike(String value) {
            addCriterion("doctor_name like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotLike(String value) {
            addCriterion("doctor_name not like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIn(List<String> values) {
            addCriterion("doctor_name in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotIn(List<String> values) {
            addCriterion("doctor_name not in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameBetween(String value1, String value2) {
            addCriterion("doctor_name between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotBetween(String value1, String value2) {
            addCriterion("doctor_name not between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleIsNull() {
            addCriterion("doctor_title is null");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleIsNotNull() {
            addCriterion("doctor_title is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleEqualTo(String value) {
            addCriterion("doctor_title =", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotEqualTo(String value) {
            addCriterion("doctor_title <>", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleGreaterThan(String value) {
            addCriterion("doctor_title >", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_title >=", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleLessThan(String value) {
            addCriterion("doctor_title <", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleLessThanOrEqualTo(String value) {
            addCriterion("doctor_title <=", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleLike(String value) {
            addCriterion("doctor_title like", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotLike(String value) {
            addCriterion("doctor_title not like", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleIn(List<String> values) {
            addCriterion("doctor_title in", values, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotIn(List<String> values) {
            addCriterion("doctor_title not in", values, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleBetween(String value1, String value2) {
            addCriterion("doctor_title between", value1, value2, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotBetween(String value1, String value2) {
            addCriterion("doctor_title not between", value1, value2, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNull() {
            addCriterion("data_status is null");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNotNull() {
            addCriterion("data_status is not null");
            return (Criteria) this;
        }

        public Criteria andDataStatusEqualTo(Byte value) {
            addCriterion("data_status =", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotEqualTo(Byte value) {
            addCriterion("data_status <>", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThan(Byte value) {
            addCriterion("data_status >", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("data_status >=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThan(Byte value) {
            addCriterion("data_status <", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThanOrEqualTo(Byte value) {
            addCriterion("data_status <=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusIn(List<Byte> values) {
            addCriterion("data_status in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotIn(List<Byte> values) {
            addCriterion("data_status not in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusBetween(Byte value1, Byte value2) {
            addCriterion("data_status between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("data_status not between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createby is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createby is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("createby =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("createby <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("createby >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("createby >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("createby <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("createby <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("createby like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("createby not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("createby in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("createby not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("createby between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("createby not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andBuildtimeIsNull() {
            addCriterion("buildtime is null");
            return (Criteria) this;
        }

        public Criteria andBuildtimeIsNotNull() {
            addCriterion("buildtime is not null");
            return (Criteria) this;
        }

        public Criteria andBuildtimeEqualTo(String value) {
            addCriterion("buildtime =", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeNotEqualTo(String value) {
            addCriterion("buildtime <>", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeGreaterThan(String value) {
            addCriterion("buildtime >", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeGreaterThanOrEqualTo(String value) {
            addCriterion("buildtime >=", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeLessThan(String value) {
            addCriterion("buildtime <", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeLessThanOrEqualTo(String value) {
            addCriterion("buildtime <=", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeLike(String value) {
            addCriterion("buildtime like", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeNotLike(String value) {
            addCriterion("buildtime not like", value, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeIn(List<String> values) {
            addCriterion("buildtime in", values, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeNotIn(List<String> values) {
            addCriterion("buildtime not in", values, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeBetween(String value1, String value2) {
            addCriterion("buildtime between", value1, value2, "buildtime");
            return (Criteria) this;
        }

        public Criteria andBuildtimeNotBetween(String value1, String value2) {
            addCriterion("buildtime not between", value1, value2, "buildtime");
            return (Criteria) this;
        }

        public Criteria andHisResultIsNull() {
            addCriterion("his_result is null");
            return (Criteria) this;
        }

        public Criteria andHisResultIsNotNull() {
            addCriterion("his_result is not null");
            return (Criteria) this;
        }

        public Criteria andHisResultEqualTo(String value) {
            addCriterion("his_result =", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultNotEqualTo(String value) {
            addCriterion("his_result <>", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultGreaterThan(String value) {
            addCriterion("his_result >", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultGreaterThanOrEqualTo(String value) {
            addCriterion("his_result >=", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultLessThan(String value) {
            addCriterion("his_result <", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultLessThanOrEqualTo(String value) {
            addCriterion("his_result <=", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultLike(String value) {
            addCriterion("his_result like", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultNotLike(String value) {
            addCriterion("his_result not like", value, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultIn(List<String> values) {
            addCriterion("his_result in", values, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultNotIn(List<String> values) {
            addCriterion("his_result not in", values, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultBetween(String value1, String value2) {
            addCriterion("his_result between", value1, value2, "hisResult");
            return (Criteria) this;
        }

        public Criteria andHisResultNotBetween(String value1, String value2) {
            addCriterion("his_result not between", value1, value2, "hisResult");
            return (Criteria) this;
        }

        public Criteria andOffertimeIsNull() {
            addCriterion("offertime is null");
            return (Criteria) this;
        }

        public Criteria andOffertimeIsNotNull() {
            addCriterion("offertime is not null");
            return (Criteria) this;
        }

        public Criteria andOffertimeEqualTo(String value) {
            addCriterion("offertime =", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeNotEqualTo(String value) {
            addCriterion("offertime <>", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeGreaterThan(String value) {
            addCriterion("offertime >", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeGreaterThanOrEqualTo(String value) {
            addCriterion("offertime >=", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeLessThan(String value) {
            addCriterion("offertime <", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeLessThanOrEqualTo(String value) {
            addCriterion("offertime <=", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeLike(String value) {
            addCriterion("offertime like", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeNotLike(String value) {
            addCriterion("offertime not like", value, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeIn(List<String> values) {
            addCriterion("offertime in", values, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeNotIn(List<String> values) {
            addCriterion("offertime not in", values, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeBetween(String value1, String value2) {
            addCriterion("offertime between", value1, value2, "offertime");
            return (Criteria) this;
        }

        public Criteria andOffertimeNotBetween(String value1, String value2) {
            addCriterion("offertime not between", value1, value2, "offertime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeIsNull() {
            addCriterion("finishtime is null");
            return (Criteria) this;
        }

        public Criteria andFinishtimeIsNotNull() {
            addCriterion("finishtime is not null");
            return (Criteria) this;
        }

        public Criteria andFinishtimeEqualTo(String value) {
            addCriterion("finishtime =", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotEqualTo(String value) {
            addCriterion("finishtime <>", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeGreaterThan(String value) {
            addCriterion("finishtime >", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeGreaterThanOrEqualTo(String value) {
            addCriterion("finishtime >=", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeLessThan(String value) {
            addCriterion("finishtime <", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeLessThanOrEqualTo(String value) {
            addCriterion("finishtime <=", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeLike(String value) {
            addCriterion("finishtime like", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotLike(String value) {
            addCriterion("finishtime not like", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeIn(List<String> values) {
            addCriterion("finishtime in", values, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotIn(List<String> values) {
            addCriterion("finishtime not in", values, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeBetween(String value1, String value2) {
            addCriterion("finishtime between", value1, value2, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotBetween(String value1, String value2) {
            addCriterion("finishtime not between", value1, value2, "finishtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Long value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Long value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Long value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Long value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Long value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Long> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Long> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Long value1, Long value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Long value1, Long value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Long value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Long value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Long value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Long value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Long value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Long> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Long> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Long value1, Long value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Long value1, Long value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdIsNull() {
            addCriterion("doctor_appointment_record_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdIsNotNull() {
            addCriterion("doctor_appointment_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdEqualTo(Long value) {
            addCriterion("doctor_appointment_record_id =", value, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdNotEqualTo(Long value) {
            addCriterion("doctor_appointment_record_id <>", value, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdGreaterThan(Long value) {
            addCriterion("doctor_appointment_record_id >", value, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("doctor_appointment_record_id >=", value, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdLessThan(Long value) {
            addCriterion("doctor_appointment_record_id <", value, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdLessThanOrEqualTo(Long value) {
            addCriterion("doctor_appointment_record_id <=", value, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdIn(List<Long> values) {
            addCriterion("doctor_appointment_record_id in", values, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdNotIn(List<Long> values) {
            addCriterion("doctor_appointment_record_id not in", values, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdBetween(Long value1, Long value2) {
            addCriterion("doctor_appointment_record_id between", value1, value2, "doctorAppointmentRecordId");
            return (Criteria) this;
        }

        public Criteria andDoctorAppointmentRecordIdNotBetween(Long value1, Long value2) {
            addCriterion("doctor_appointment_record_id not between", value1, value2, "doctorAppointmentRecordId");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}