package org.lemonframework.generator.plugin;

import java.util.List;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.internal.DefaultCommentGenerator;

/**
 * 生成model中，字段增加注释.
 *
 * @author jiawei zhang
 * @since 0.0.1
 */
public class CommentGenerator extends DefaultCommentGenerator {

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        super.addFieldComment(field, introspectedTable, introspectedColumn);
        if (introspectedColumn.getRemarks() != null && !"".equals(introspectedColumn.getRemarks())) {
            field.addJavaDocLine("/**");
            field.addJavaDocLine(" * " + introspectedColumn.getRemarks() + ".");
            addJavadocTag(field, false);
            field.addJavaDocLine(" */");
        } else {
            field.addJavaDocLine("/**");
            field.addJavaDocLine(" * " + field.getName() + ".");
            addJavadocTag(field, false);
            field.addJavaDocLine(" */");
        }
    }

    @Override
    public void addGeneralMethodComment(Method method, IntrospectedTable introspectedTable) {
        super.addGeneralMethodComment(method, introspectedTable);
        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/**");
        method
                .addJavaDocLine(" * This method was generated by MyBatis Generator.");

        final List<Parameter> parameters = method.getParameters();
        for(int i = 0; i < parameters.size(); i++) {
            final Parameter parameter = parameters.get(i);
            method.addJavaDocLine(" * @param " + parameter.getName() + " " + parameter.getName());
        }
        final FullyQualifiedJavaType returnType = method.getReturnType();
        if (returnType == null) {
            method.addJavaDocLine(" * @return");
        } else {
            method.addJavaDocLine(" * @return " + returnType.getShortName());
        }

        addJavadocTag(method, false);
        method.addJavaDocLine(" */");
    }
}
