package org.lemonframework.generator.sample.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonframework.generator.sample.dao.model.AppointmentRecord1;
import org.lemonframework.generator.sample.dao.model.AppointmentRecord1Example;

public interface AppointmentRecord1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return long
     *
     * @mbg.generated
     */
    long countByExample(AppointmentRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int deleteByExample(AppointmentRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return int
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insert(AppointmentRecord1 record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insertSelective(AppointmentRecord1 record);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return List<AppointmentRecord1>
     *
     * @mbg.generated
     */
    List<AppointmentRecord1> selectByExample(AppointmentRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return AppointmentRecord1
     *
     * @mbg.generated
     */
    AppointmentRecord1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppointmentRecord1 record, @Param("example") AppointmentRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppointmentRecord1 record, @Param("example") AppointmentRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppointmentRecord1 record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppointmentRecord1 record);
}