package org.lemonframework.generator.sample.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonframework.generator.sample.dao.model.AppointmentRecord;
import org.lemonframework.generator.sample.dao.model.AppointmentRecordExample;

public interface AppointmentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return long
     *
     * @mbg.generated
     */
    long countByExample(AppointmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int deleteByExample(AppointmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return int
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insert(AppointmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insertSelective(AppointmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return List<AppointmentRecord>
     *
     * @mbg.generated
     */
    List<AppointmentRecord> selectByExample(AppointmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return AppointmentRecord
     *
     * @mbg.generated
     */
    AppointmentRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppointmentRecord record, @Param("example") AppointmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppointmentRecord record, @Param("example") AppointmentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppointmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppointmentRecord record);
}