package org.lemonframework.generator.sample.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonframework.generator.sample.dao.model.Person;
import org.lemonframework.generator.sample.dao.model.PersonExample;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return long
     *
     * @mbg.generated
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return int
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return List<Person>
     *
     * @mbg.generated
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return Person
     *
     * @mbg.generated
     */
    Person selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Person record);
}