package org.lemonframework.generator.sample.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonframework.generator.sample.dao.model.TradeOrderRecord;
import org.lemonframework.generator.sample.dao.model.TradeOrderRecordExample;

public interface TradeOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return long
     *
     * @mbg.generated
     */
    long countByExample(TradeOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int deleteByExample(TradeOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return int
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insert(TradeOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insertSelective(TradeOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return List<TradeOrderRecord>
     *
     * @mbg.generated
     */
    List<TradeOrderRecord> selectByExample(TradeOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return TradeOrderRecord
     *
     * @mbg.generated
     */
    TradeOrderRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeOrderRecord record, @Param("example") TradeOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeOrderRecord record, @Param("example") TradeOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeOrderRecord record);
}