package org.lemonframework.generator.sample.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonframework.generator.sample.dao.model.TradeOrderRecord1;
import org.lemonframework.generator.sample.dao.model.TradeOrderRecord1Example;

public interface TradeOrderRecord1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return long
     *
     * @mbg.generated
     */
    long countByExample(TradeOrderRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int deleteByExample(TradeOrderRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return int
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insert(TradeOrderRecord1 record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int insertSelective(TradeOrderRecord1 record);

    /**
     * This method was generated by MyBatis Generator.
     * @param example example
     * @return List<TradeOrderRecord1>
     *
     * @mbg.generated
     */
    List<TradeOrderRecord1> selectByExample(TradeOrderRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param id id
     * @return TradeOrderRecord1
     *
     * @mbg.generated
     */
    TradeOrderRecord1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeOrderRecord1 record, @Param("example") TradeOrderRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @param example example
     * @return int
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeOrderRecord1 record, @Param("example") TradeOrderRecord1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeOrderRecord1 record);

    /**
     * This method was generated by MyBatis Generator.
     * @param record record
     * @return int
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeOrderRecord1 record);
}